version: '3'
services: 
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  mysql_database:
    container_name: mysql
    image: "mysql:5.7"
    restart: always
    environment:
      MYSQL_DATABASE: 'dbvivitech'
      MYSQL_ROOT_PASSWORD: 'swordfish'
    ports:
      - 3306:3306

